# ============================================================
# universe_builder.py — v4
# Complete NSE ticker map for 1,300+ companies from screener.in
# ============================================================

import re, sys
import pandas as pd
from pathlib import Path
from datetime import datetime
from collections import Counter
from database import init_db, upsert_universe, get_universe

EXPORT_PATH = Path("data/screener_export.csv")

KNOWN_TICKERS = {
    # A
    'a b lifestyle':'ABFRL','a b real estate':'ABREALESTATE',
    'a c j k exports':'ACJKEXPORTS','a k capital serv':'AKCAPITALSERVICES',
    'a.k.capital serv':'AKCAPITALSERVICES','aarti drugs':'AARTIDRUGS',
    'aarti industries':'AARTIIND','aarti pharma':'AARTIPHARMALABS',
    'aavas financiers':'AAVAS','aadhar hsg. fin.':'AADHARHFC',
    'acc':'ACC','accelya solution':'ACCELYA','accent microcell':'ACCENTMIC',
    'acme solar hold.':'ACMESOLAR','acutaas chemical':'ACUTAAS',
    'action const.eq.':'ACE','ador welding':'ADORWELD',
    'adf foods':'ADFFOODS','advanced enzyme':'ADVENZYMES',
    'advait energy':'ADVAITEPC','aegis logistics':'AEGISLOG',
    'aegis vopak term':'AEGISVOPAK','aeroflex':'AEROFLEX',
    'aeroflex enter.':'AEROFLEXIND','afcom holdings':'AFCOM',
    'afcons infrastr.':'AFCONS','agi infra':'AGIIL',
    'agi greenpac':'AGIGREENPAC','aia engineering':'AIAENG',
    'ahluwalia contr.':'AHLUCONT','ajax engineering':'AJAXENGG',
    'ajanta pharma':'AJANTPHARM','ajmera realty':'AJMERA',
    'akums drugs':'AKUMS','alkyl amines':'ALKYLAMINESCHEM',
    'alembic':'ALEMBIC','alembic pharma':'ALEMBICLTD',
    'alicon cast.':'ALICON','alldigi tech':'ALLDIGI',
    'all time plastic':'ALLTIMEPL','allcargo logist.':'ALLCARGO',
    'allied blenders':'ABDL','alok industries':'ALOKINDS',
    'alpex solar':'ALPEXSOLAR','altius telecom':'ALTIUSTECOM',
    'amber enterp.':'AMBER','amara raja ener.':'AMARARAJABAT',
    'amrutanjan healt':'AMRUTANJAN','amic forging':'AMICORP',
    'aether industri.':'AETHER','affle 3i':'AFFLE',
    'anand rathi shar':'ANANDRATHISHA','anand rathi wea.':'ANANDRATHI',
    'angel one':'ANGELONE','anant raj':'ANANTRAJ',
    'anantam highways':'ANANTAMHW','andhra paper':'ANDHRAPAPER',
    'andhra sugars':'ANDHRSUGAR','anthem bioscienc':'ANTHEMBIOSCIENCES',
    'antelopus selan':'ANTELOPUS','anupam rasayan':'ANUPAMRASAYAN',
    'apar inds.':'APARINDS','apex frozen food':'APEXFROZENFOOD',
    'apollo micro sys':'APOLLOMICRO','apollo pipes':'APOLLOPIPE',
    'apollo tyres':'APOLLOTYRE','apcotex industri':'APCOTEX',
    'aptus value hou.':'APTUS','aqylon nexus':'AQYLON',
    'archean chemical':'ARCHEAN','arfin india':'ARFIN',
    'arihant super.':'ARIHANTSUPE','arman financial':'ARMANFIN',
    'arvind fashions.':'ARVINDFA','arvind ltd':'ARVIND',
    'arvind smartsp.':'ARVINDSMART','asahi india glas':'ASAHIINDIA',
    'ashiana housing':'ASHIANA','ashapura minech.':'ASHAPURAMIN',
    'ask automotive':'ASKAUTOMOTIVE','asm technologies':'ASMTECH',
    'astec lifescienc':'ASTECLTD','astral':'ASTRAL',
    'astra microwave':'ASTRAMICRO','astrazeneca phar':'ASTRAZEN',
    'aster dm health.':'ASTERDM','assoc.alcohols':'ASSOCINDUS',
    'atlanta electric':'ATGL','authum invest':'AUTHUM',
    'automotive axles':'AUTOAXLES','avantel':'AVANTEL',
    'avanti feeds':'AVANTIFEED','awfis space':'AWFIS',
    'awl agri busine.':'AWLAGRI','aurionpro sol.':'AURIONPRO',
    'aym syntex':'AYMSYNTEX','aye finance':'AYEFINANCE',
    'azad engineering':'AZAD','axiscades tech.':'AXISCADES',
    'aequs':'AEQUS','axis solution':'AXISSOLUTION',
    'aditya amc':'ADITYABIRLAAMC','aditya bir. fas.':'ADBRILFASH',
    'aditya infotech':'ADITYAINFO','aditya vision':'ADITYAVISION',
    'andrew yule & co':'ANDREWYULE','anzen iyep trust':'ANZENINVIT',
    'arkade':'ARKADE','aurum proptech':'AURUMPROP',
    'avishkar infra':'AVISHKAR','aayush art':'AAYUSHFOOD',
    # B
    'b.l.kashyap':'BLKASHYAP','bajaj consumer':'BAJAJCON',
    'bajaj electrical':'BAJAJELEC','bajaj healthcare':'BAJAJHCARE',
    'bajaj hindusthan':'BAJAJHIND','balkrishna inds':'BALKRISIND',
    'balaji amines':'BALAMINES','balaji telefilms':'BALAJITELE',
    'balmer law. inv.':'BALMLAWRIE','balmer lawrie':'BALMLAWRIE',
    'balrampur chini':'BALRAMCHIN','balu forge':'BALUFORGE',
    'bansal wire inds':'BANSALWIRE','bannari amm.sug.':'BANARISUG',
    'bandhan bank':'BANDHANBNK','basf india':'BASF',
    'bata india':'BATAINDIA','bayer crop sci.':'BAYERCROP',
    'bcl industries':'BCLIND','beml ltd':'BEML',
    'belrise industri':'BELRISE','benares hotels':'BENARAS',
    'bengal & assam':'BENGALASSAM','bf investment':'BFINVESTMENT',
    'bf utilities':'BFU','bharat bijlee':'BHARATBIJLEE',
    'bharat coking':'BHARATCOKING','bharat global':'BHARATGLOBL',
    'bharat rasayan':'BHARATRAS','bharat seats':'BHARATSEATS',
    'bharat wire':'BHARATWIRE','bhansali engg.':'BHANSALIENG',
    'bhagiradha chem.':'BHAGIRADHA','bikaji foods':'BIKAJI',
    'birla corpn.':'BIRLACORPN','birlasoft ltd':'BIRLASOFT',
    'birlanu ltd':'BIRLANU','blackbuck':'BLACKBUCK',
    'bls e-services':'BLSINFO','bls internat.':'BLSINTERNATIONAL',
    'bliss gvs pharma':'BLISSGVS','blue cloud soft.':'BLUECLOUD',
    'blue dart expres':'BLUEDART','blue jet health':'BLUEJET',
    'blue pearl agri':'BLUEPEARLAGRI','blue star':'BLUESTARCO',
    'bn agrochem':'BNAGROCHEM','borosil':'BOROLTD',
    'borosil renew.':'BORORENEW','borosil scienti.':'BSCIENTIFIC',
    'bombay dyeing':'BOMBDYEING','bombay super hyb':'BOMBAYSUPE',
    'bondada engineer':'BONDADA','brainbees solut.':'FIRSTCRY',
    'brigade enterpr.':'BRIGADE','brigade hotel':'BHFL',
    'brightcom group':'BRIGHTCOM','brookfield india':'BIRET',
    'butterfly gan ap':'BUTTERFLY','baazar style':'BAAZARSTYLE',
    'bg energy sys.':'BGRENERGY','bgr energy sys.':'BGRENERGY',
    # C
    'c d s l':'CDSL','c p c l':'CPCL','c.e. info system':'MAPMYINDIA',
    'camlin fine':'CAMLIN','campus activewe.':'CAMPUS',
    'can fin homes':'CANFINHOME','canara robeco':'CANARAROBECO',
    'canara hsbc':'CANARAHSBCLIFE','capacite infra.':'CAPACITE',
    'caplin point lab':'CAPLIPOINT','capri global':'CAPRIGLOBAL',
    'capillary tech.':'CAPILLARYTECH','care ratings':'CARERATING',
    'carraro india':'CARRARO','cartrade tech':'CARTRADE',
    'castrol india':'CASTROLIND','ceat':'CEAT',
    'ceigall india':'CEIGALL','ceinsys tech':'CEINSYS',
    'cello world':'CELLO','cemindia project':'CEMINDIA',
    'cera sanitary.':'CERA','century plyboard':'CENTURYPLY',
    'centum electron':'CENTUM','cesc':'CESC',
    'cff fluid':'CFFFLUID','chamanlal setia':'CHAMANSETICA',
    'chambal fert.':'CHAMBLFERT','chalet hotels':'CHALETHOTELS',
    'choice intl.':'CHOICEIN','chemplast sanmar':'CHEMPLASTS',
    'chola financial':'CHOLAFIN','cie automotive':'CIEINDIA',
    'cigniti tech.':'CIGNITITEC','city pulse multi':'CITYPULSE',
    'city union bank':'CUB','clean max enviro':'CLEANMAX',
    'clean science':'CLEANSCIENCE','cms info systems':'CMSINFO',
    'coforge':'COFORGE','colab platforms':'COLAB',
    'cohance life':'COHANCELIFE','cochin shipyard':'COCHINSHIP',
    'concord biotech':'CONCORDBIO','concord control':'CONCORDENV',
    'confidence petro':'CONFIPET','container corpn.':'CONCOR',
    'control print':'CONTROLPRINT','corona remedies':'CORONA',
    'cosmo first':'COSMOFIRST','craftsman auto':'CRAFTSMAN',
    'creditacc. gram.':'CREDITACC','crisil':'CRISIL',
    'crompton gr. con':'CROMPTON','crizac':'CRIZAC',
    'csb bank':'CSBBANK','cube highways':'CUBEHIGHWAY',
    'cupid':'CUPID','cyient':'CYIENT',
    'cyient dlm':'CYIENTDLM','ccl products':'CCLPROD',
    'cams services':'CAMS','capital infra':'CAPITALINFRA',
    'capital india':'CAPITALIND','capital small':'CAPITALSFB',
    'centrum capital':'CENTRUM',
    # D
    'd b corp':'DBCORP','d-link india':'DLINK',
    'd.p. abhushan':'DPABHUSHAN','dalmia bharat':'DALMIABHA',
    'dalmia bharatltd':'DALMIABHA','dam capital advi':'DAMCAP',
    'danish power':'DANISHPOWER','data pattern':'DATAPATTNS',
    'datamatics glob.':'DATAMATICS','dcb bank':'DCBBANK',
    'dcm shriram':'DCMSHRIRAM','dcw':'DCW',
    'dec.gold mines':'DECOLDMINES','deepak fertilis.':'DEEPAKFERT',
    'deepak nitrite':'DEEPAKNTR','ddev plastiks':'DDEVPLAST',
    'dee development':'DEEDEVELOPMENT','delhivery':'DELHIVERY',
    'delta corp':'DELTACORP','den networks':'DNET',
    'devyani intl.':'DEVYANI','diffusion eng':'DIFFUSION',
    'dilip buildcon':'DALBHARAT','disa india':'DISA',
    'dishman carbogen':'DCAL','divgi torq':'DIVGIITTS',
    'dodla dairy':'DODLA','dolat algotech':'DOLATALGO',
    'dollar industrie':'DOLLAR','dolphin offshore':'DOLPHINOFF',
    'doms industries':'DOMS','dr agarwal\'s eye':'DRAGARWALS',
    'dr agarwal\'s hea':'DRAGARWALSEYE','dr lal pathlabs':'LALPATHLAB',
    'dredging corpn.':'DREDGECORP','dynamatic tech.':'DYNAMATECH',
    'dynamic cables':'DYNAMICCAB','dcx systems':'DCXSYS',
    'dhanlaxmi bank':'DHANBANK','dhenu buildcon':'DHENU',
    'divine power':'DIVINEPOWER',
    # E
    'e2e networks':'E2ENETWORKS','easy trip plann.':'EASEMYTRIP',
    'edelweiss.fin.':'EDELWEISS','efc (i)':'EFCIND',
    'eih':'EIHOTEL','eih assoc.hotels':'EIHAHOTELS',
    'elantas beck':'ELANTAS','electrost.cast.':'ELECTROSTEEL',
    'elecon engg.co':'ELECON','electronics mart':'ELIN',
    'elpro internatio':'ELPRO','elgi equipments':'ELGIEQUIP',
    'ellen.indl.gas':'ELLENBARRIE','elcid investment':'ELCID',
    'emcure pharma':'EMCURE','emami':'EMAMILTD',
    'embassy off.reit':'EMBASSY','embassy develop':'EMBASSYDEVEL',
    'emmvee photovol.':'EMMVEE','ems':'EMSL',
    'endurance tech.':'ENDURANCE','energy inftrust':'POWERGRID',
    'engineers india':'ENGINERSIN','enviro infra':'ENVIROINFRA',
    'epigral':'EPIGRAL','epack durable':'EPACKDURABLE',
    'epack prefabtech':'EPACK','epl ltd':'EPL',
    'eris lifescience':'ERIS','esab india':'ESABINDIA',
    'esaf small fin':'ESAFSFB','ethos':'ETHOS',
    'euro pratik sale':'EUROIND','eureka forbes':'EUREKAFORBES',
    'eveready inds.':'EVEREADY','excel industries':'EXCELINDUS',
    'exide inds.':'EXIDEIND','exicom tele-sys.':'EXICOM',
    'expleo solutions':'EXPLEOSOL','emkay tools':'EMKAYTOOLS',
    'elitecon inter.':'ELITECON','embassy off.reit':'EMBASSY',
    # F
    'faze three':'FAZETHREE','fdc':'FDC',
    'fedbank financi.':'FEDFINA','federal-mogul go':'FEDERALMOGU',
    'fiem industries':'FIEMIND','filatex india':'FILATEX',
    'fine organic':'FINEORG','fineotex chem':'FINEOTEX',
    'fino payments':'FINOPB','finolex cables':'FINCABLES',
    'finolex inds.':'FINPIPE','firstsour.solu.':'FIRSTSOURCE',
    'five-star bus.fi':'FIVESTAR','flair writing':'FLAIR',
    'force motors':'FORCEMOT','foseco india':'FOSECOIND',
    'fractal analyt.':'FRACTALAI','frontier springs':'FRONTIER',
    'fujiyama power':'FUJIYAMA','fusion finance':'FUSION',
    'fredun pharma':'FREDUN','fischer medical':'FISCHERMED',
    # G
    'g m breweries':'GMBREW','g m d c':'GMDC',
    'g n f c':'GNFC','g r infraproject':'GRINFRA',
    'g s f c':'GSFC','gabriel india':'GABRIEL',
    'galaxy surfact.':'GALAXYSURFACT','gallantt ispat l':'GALLANTT',
    'gandhar oil ref.':'GANDHAR','gandhi spl. tube':'GANDHITUBE',
    'ganesha ecosphe.':'GANESHHOUC','garuda cons':'GARUDACONS',
    'garware hi tech':'GARWARETECH','garware tech.':'GARWARETECH',
    'gateway distri':'GATEWAYDISTRIPARK','ge shipping co':'GESHIP',
    'genesys intl.':'GENESYS','genus power':'GENUSPOWER',
    'geojit fin. ser.':'GEOJITFSL','ghcl':'GHCL',
    'gk energy':'GKENERGY','glaxosmi. pharma':'GLAXO',
    'global health':'MANKIND','globus spirits':'GLOBUSSPR',
    'gna axles':'GNAAXLES','gng electronics':'GNGELECTRONICS',
    'godavari bioref.':'GODAVARBIORE','godawari power':'GPIL',
    'gocl corpn.':'GOCLCORP','godfrey phillips':'GODFRYPHLP',
    'godrej agrovet':'GODREJAGRO','godrej industrie':'GODREJIND',
    'gokaldas exports':'GOKALDAS','gokul agro':'GOKULAGRO',
    'go digit general':'GODIGIT','go fashion (i)':'GOCOLORS',
    'goodluck india':'GOODLUCK','gopal snacks':'GOPAL',
    'goodyear india':'GOODYEAR','gpt healthcare':'GPTHEALTH',
    'gpt infraproject':'GPTINFRA','graphite india':'GRAPHITE',
    'gravita india':'GRAVITA','grauer & weil':'GRAUER',
    'greaves cotton':'GREAVESCOT','greenlam industr':'GREENLAM',
    'greenply industr':'GREENPLY','greenpanel inds.':'GREENPANEL',
    'grindwell norton':'GRINDWELL','grm overseas':'GRMOVER',
    'grp':'GRP','gufic bioscience':'GUFICBIO',
    'gujarat alkalies':'GUJALKALI','gujarat fluoroch':'FLUOROCHEM',
    'gujarat gas':'GUJGAS','guj inds. power':'GIPCL',
    'guj pipavav port':'GPPL','guj.st.petronet':'GSPL',
    'guj.nat.resour.':'GUJNRE','guj. ambuja exp':'GUJAMBEX',
    'guj. themis bio.':'THEMISMED','gulf oil lubric.':'GULFOILLUB',
    'gulshan polyols':'GULSHAN','ge power':'GEPIL',
    'ghv infra':'GHVINFRA','grand oak canyon':'GRANDOAK',
    'gsp crop science':'GSPCROPS','gmr urban':'GMRPINFRA',
    # H
    'h g infra engg.':'HGINFRA','h u d c o':'HUDCO',
    'happy forgings':'HAPPYFORGINGS','hardwyn india':'HARDWYN',
    'harsha engg intl':'HARSHA','haryana fin. co.':'HARYANAFINCO',
    'hatsun agro':'HATSUN','hawkins cookers':'HAWKINCOOK',
    'hbl engineering':'HBLPOWER','heg':'HEG',
    'heritage foods':'HERITGFOOD','hester bios':'HESTERBIO',
    'hexaware tech.':'HEXAWARE','hfcl':'HFCL',
    'hikal':'HIKAL','himadri special':'HIMADRI',
    'himatsing. seide':'HIMATSEIDE','hind rectifiers':'HINDRECTIF',
    'hind.construct.':'HCC','hind.oil explor.':'HINDOILEXP',
    'hinduja global':'HINDUJAGLOBAL','hindware home in':'HINDWAREAP',
    'home first finan':'HOMEFIRST','honda india':'HMCL',
    'honasa consumer':'HONASA','honeywell auto':'HONAUT',
    'hpl electric':'HPLELEC','hubtown':'HUBTOWN',
    'huhtamaki india':'HUHTAMAKI','hmt':'HMT',
    'hypersoft tech.':'HYPERSOFT',
    # I
    'i g petrochems':'IGPL','i r c t c':'IRCTC',
    'i t d c':'ITDC','icra':'ICRA',
    'ideaforge tech':'IDEAFORGE','ifci':'IFCI',
    'ifgl refractori.':'IFGLEXPRO','igarashi motors':'IGARASHI',
    'iifl capital':'IIFLCAP','iifl finance':'IIFL',
    'ikio tech':'IKIO','imagica. enter.':'IMAGICAWORLD',
    'india glycols':'INDIAGLYCO','india motor part':'INDIAMOTOR',
    'india nipp.elec.':'INDIANITEC','india pesticides':'INDIAPEST',
    'india cements':'INDIACEM','indian energy ex':'IEX',
    'indian hume pipe':'INDIANHUME','indian metals':'IMFA',
    'indian renewable':'IREDA','indiamart inter.':'INDIAMART',
    'indegene':'INDEGENE','indo count inds.':'ICIL',
    'indo thai sec.':'INDOTHAI','indo tech.trans.':'INDOTECHTR',
    'indokem':'INDOKEM','indosolar':'INDOSOLAR',
    'indostar capital':'INDOSTAR','indrapr.medical':'INDRAMEDCO',
    'indus inf. trust':'INDIGRID','indiqube spaces':'INDIGUBSPA',
    'indl.& prud.inv.':'IPAPPM','indoco remedies':'INDOCO',
    'indigo paints':'INDIGOPNTS','inox green':'INOXGREEN',
    'inox india':'INOXINDIA','inox wind':'INOXWIND',
    'insolation ener':'INSOLATION','insecticid.india':'INSECTICID',
    'interarch build.':'INTERARCH','international ge':'IGRID',
    'inventurus knowl':'INVENTURUS',
    'ion exchange':'IONEXCHANG','ipca labs.':'IPCALAB',
    'irb infra.devl.':'IRB','irb invit fund':'IRBINVIT',
    'ircon intl.':'IRCON','irm energy':'IRMENERGY',
    'isgec heavy':'ISGEC','itc hotels':'ITCHOTELS',
    'iti':'ITI','ivalue infosolut':'IVALUE',
    'izmo':'IZMO','ice make refrig.':'ICEMAKE',
    'indiabulls':'IBULHSGFIN','india shelte fin':'INDIASHLTR',
    'ind-swift labs.':'INDSWFTLAB',
    # J
    'j & k bank':'JKBANK','j b chemicals &':'JBCHEPHARM',
    'j g chemicals':'JGCHEM','j k cements':'JKCEMENT',
    'j kumar infra':'JKUMAR','jagran prakashan':'JAGRAN',
    'jagsonpal pharma':'JAGSONPAL','jai balaji inds.':'JAIBALAJI',
    'jai corp':'JAICORP','jain irrigation':'JAINAM',
    'jain resource':'JAINRES','jamna auto inds.':'JAMNA',
    'jana small finan':'JANASFB','jash engineering':'JASH',
    'jay bharat maru.':'JAYBHARTAM','jayaswal neco':'JAYASWALNEO',
    'jk lakshmi cem.':'JKLAKSHMI','jk paper':'JKPAPER',
    'jk tyre & indust':'JKTYRE','jm financial':'JMFINANCL',
    'jnk':'JNKBHARAT','jindal drilling':'JINDALDRIL',
    'jindal photo':'JINDALPHOT','jindal poly film':'JINDALPOLY',
    'jindal poly inve':'JPINFRA','jindal saw':'JINDALSAW',
    'jindal worldwide':'JINDALWORLDWIDE','john cockerill':'JOHNCOCKERILL',
    'jp power ven.':'JPPOWER','jsw cement':'JSWCEMENT',
    'jsw dulux':'JSWDULUX','jsw holdings':'JSWHL',
    'jtekt india':'JTEKTINDIA','jubilant agri':'JUBLAGRI',
    'jubilant food.':'JUBLFOOD','jubilant ingrev.':'JUBLBIOSYS',
    'jubilant pharmo':'JUBPHARMOVA','jupiter life lin':'JUPITERLIFEINSUR',
    'jupiter wagons':'JWL','just dial':'JUSTDIAL',
    'jyothy labs':'JYOTHYLAB','jyoti cnc auto.':'JYOTICNC',
    'jyoti resins':'JYOTIRESNS','jyoti structures':'JYOTISTRUC',
    'juniper hotels':'JUNIPER',
    # K
    'k c p':'KCP','k p energy':'KPEL',
    'k p r mill ltd':'KPRMILL','kajaria ceramics':'KAJARIACER',
    'kalpat.':'KALPATARUPR','kalpataru proj.':'KALPATARUPR',
    'kalyani invest.':'KALYANIINV','kalyani steels':'KALYANISTEELS',
    'kalyan jewellers':'KALYANKJIL','kama holdings':'KAMADRUG',
    'kansai nerolac':'KANSAINER','kapston services':'KAPSTON',
    'karnataka bank':'KTKBANK','karur vysya bank':'KVB',
    'kaveri seed co.':'KAVERISED','kaynes tech':'KAYNES',
    'kddl ltd':'KDDL','kec international':'KEC',
    'kei industries':'KEI','kennametal india':'KENNAMET',
    'kernex microsys.':'KERNEX','kewal kir.cloth.':'KEWALIND',
    'keystone realtor':'KEYSTONEREALTY','kfin technolog.':'KFINTECH',
    'khazanchi jewell':'KHAZANCHI','kingfa science':'KINGFA',
    'kiri industries':'KIRIINDUS','kirloskar indus.':'KIRLOSIND',
    'kirloskar oil':'KIRLOSKAR','kirl. brothers':'KIRLBROS',
    'kirl. ferrous':'KIRLOSFERR','kirl.pneumatic':'KIRLPNU',
    'kitex garments':'KITEX','knr construct.':'KNRCON',
    'knowledge marine':'KNOWLEDGEM','kolte patil dev.':'KOLTEPATIL',
    'kovai medical':'KOVAI','kp green engg.':'KPGREEN',
    'kpit technologi.':'KPITTECH','krbl':'KRBL',
    'krishana phosch.':'KRISHNAPH','krishna defence':'KRISHNADEF',
    'krishna institu.':'KIE','kross ltd':'KROSS',
    'krsnaa diagnost.':'KRSNA','ksb':'KSB',
    'ksh internationa':'KSHITIJPOL','kmc speciality':'KMCSHIL',
    'kpi green energy':'KPIGREEN','kdrn heat exchan':'KRNHEATEX',
    'krn heat exchan':'KRNHEATEX','ks smart technlogies':'KSST',
    # L
    'l g balakrishnan':'LGB','l t foods':'LTFOODS',
    'l&t technology':'LTTS','landmark cars':'LANDMARK',
    'la opala rg':'LAOPALA','latent view':'LATENTVIEW',
    'laxmi dental':'LAXMIORTHO','laxmi goldorna':'LAXMIGOLD',
    'laxmi organic':'LAXMICHEM','leela palaces hotels':'LEELA',
    'le merite export':'LEMERITE','le travenues':'IXIGO',
    'lic housing fin.':'LICHSGFIN','lincoln pharma.':'LINCOLNPHAR',
    'lkp finance':'LKPFIN','lloyds enterpris':'LLOYDSENGG',
    'lloyds engineeri':'LLOYDSENT','lmw':'LAKSHMANR',
    'lux industries':'LUXIND','lumax auto tech.':'LUMAXAUTOTECH',
    'lumax industries':'LUMAXIND','lemon tree hotel':'LEMONTREE',
    'le merite export':'LEMERITE',
    # M
    'm & b engineer.':'MBEENGG','m & m fin. serv.':'M&MFIN',
    'm b agro prod.':'MBAGRO','m m forgings':'MMFL',
    'm r p l':'MRPL','m t n l':'MTNL',
    'magellanic cloud':'MAGELANIC','mah. seamless':'MAHSEAMLES',
    'mah. scooters':'MAHSCOOTER','mahamaya steel':'MAHAMAYA',
    'mahanagar gas':'MGL','mahindra holiday':'MHRIL',
    'mahindra life.':'MAHLIFE','mahindra logis.':'MAHLOG',
    'maithan alloys':'MAITHANALL','man industries':'MANINDS',
    'man infra':'MANINFRA','manappuram fin.':'MANAPPURAM',
    'mangalam cement':'MANGLMCEM','manaksia coated':'MANAKCOAT',
    'manorama indust.':'MANORGANICS','maple inf. trust':'MIPLSCHEMES',
    'marathon nextgen':'MARATHON','marine electric.':'MARINEELEC',
    'marksans pharma':'MARKSANS','mas financ ser':'MAS',
    'mastek':'MASTECH','mayur uniquoters':'MAYURUNIQ',
    'medplus health':'MEDPLUS','medi assist ser.':'MEDIASSIST',
    'media matrix':'MEDIAMATRIX','meghmani organi.':'MEGHMANIND',
    'meghna infracon':'MEGHNA','metro brands':'METROBRAND',
    'midwest':'MIDWEST','midwest gold':'MIDWESTGOLD',
    'minda corp':'MINDACORP','mindspace busine':'MINDSPACE',
    'mirc electronics':'MIRC','mishra dhatu nig':'MIDHANI',
    'mmtc':'MMTC','moil':'MOIL',
    'mold-tek pack.':'MOLDTKPAC','monte carlo fas.':'MONTECARLO',
    'morepen labs.':'MOREPENLAB','moschip tech.':'MOSCHIP',
    'motil.oswal.fin.':'MOTILALOFS','motisons jewel':'MOTISONS',
    'mphasis':'MPHASIS','mrs bectors':'BECTORFOOD',
    'mps':'MPSLTD','mstc':'MSTCLTD',
    'mtar technologie':'MTARTECH','mufin green':'MUFINGREEN',
    'mukand':'MUKAND','muthoot microfin':'MUTHOOTMF',
    'mas financ ser':'MAS','modern insulator':'MODERNINSL',
    'msp steel & pow.':'MSPSTEEL','mtar technologie':'MTARTECH',
    # N
    'n s d l':'NSDL','nacl industries':'NACLIND',
    'nalwa sons invst':'NALWASONS','narayana hrudaya':'NH',
    'natco pharma':'NATCOPHARM','natl.fertilizer':'NFL',
    'national high':'NATHIGHWAY','national standar':'NSIL',
    'navin fluo.intl.':'NAVINFLUOR','navkar corporat.':'NAVKARCORP',
    'navneet educat.':'NAVNETEDUL','nazara technolo.':'NAZARA',
    'nbcc':'NBCC','ncc':'NCC',
    'ndr auto compon.':'NDRAUTO','ndr invit trust':'NDRINVIT',
    'nelcast':'NELCAST','nelco':'NELCO',
    'nephrocare health services':'NEPHRO','nesco':'NESCO',
    'neogen chemicals':'NEOGEN','neuland labs.':'NEULANDLAB',
    'neueon corporation':'NEUEON','network people':'NPST',
    'netweb technol.':'NETWEB','newgen software':'NEWGEN',
    'nexus select':'NEXUSSELECT','ngl fine chem':'NGLFINECHEM',
    'niit learning':'NIITLTD','nilkamal ltd':'NILKAMAL',
    'nitco':'NITCO','niva bupa health':'NIVABUPA',
    'nlc india':'NLCINDIA','nmdc steel':'NMDCSTEEL',
    'nocil':'NOCIL','novartis india':'NOVARTIND',
    'nrb bearings':'NRBBEARING','nuvama wealth':'NUVAMA',
    'nuvoco vistas':'NUVOCO','northern arc':'NORTHARC',
    'new india assura':'NIACL','ndrinvit trust':'NDRINVIT',
    # O
    'olectra greentec':'OLECTRA','omaxe':'OMAXE',
    'omnitech engg.':'OMNITECH','one mobikwik':'MOBIKWIK',
    'one global serv':'ONEGLOBAL','one point one':'ONEPOINT',
    'onesource speci.':'ONESOURCE','orient cement':'ORIENTCEM',
    'orient electric':'ORIENTELEC','orient green':'ORIENTGREEN',
    'orient tech.':'ORIENTTECH','oriental aromat.':'ORIENTALAROM',
    'oriental hotels':'ORIENTHOTEL','orchid pharma':'ORCHPHARMA',
    'orissa minerals':'ORISSAMINE','orkla india':'NUTRILA',
    'oswal pumps':'OSWALPUMPS','onix solar':'ONIXSOLAR',
    'ola electric':'OLAELEC','ather energy':'ATHER',
    # P
    'p & g health ltd':'PGHH','p & g hygiene':'PGHH',
    'p i industries':'PIIND','p n gadgil jewe.':'PNGJL',
    'page industries':'PAGEIND','paisalo digital':'PAISALO',
    'panacea biotec':'PANACEABIOTC','panama petrochem':'PANAMAPET',
    'panorama studios':'PANORAMAST','parag milk foods':'PARAGMILK',
    'paras defence':'PARAS','paramount comm.':'PARAMOUNT',
    'park medi world':'PARKMEDIWORLD','pashupati cotsp.':'PASHUPATI',
    'patel engineerin':'PATELENG','pc jeweller':'PCJEWELLER',
    'pcbl chemical':'PCBL','pds':'PDSL',
    'pennar industrie':'PENNARINT','pfizer':'PFIZER',
    'pg electroplast':'PGEL','pine labs':'PINELABS',
    'pilani invest.':'PILANI','pitti engg.':'PITTIE',
    'pix transmission':'PIXTRANS','pnb gilts':'PNBGILTS',
    'pnb housing':'PNBHOUSING','pngs reva diamo.':'PNGSREVA',
    'platinum industr':'PLATIND','poly medicure':'POLYMED',
    'polyplex corpn':'POLYPLEX','pondy oxides':'PONDYOXIDE',
    'poonawalla fin':'POONAWLAFIN','power mech proj.':'POWERMECH',
    'powergrid infra.':'PGIL','powerica ltd':'POWERICA',
    'praj industries':'PRAJIND','prakash industri':'PRAKASH',
    'prataap snacks':'DIAMONDYD','prec. wires (i)':'PRECWIRE',
    'prem. explosives':'PREMEXPLN','premier energies':'PREMIENERGY',
    'pricol ltd':'PRICOLLTD','prime focus':'PFOCUS',
    'prince pipes':'PRINCEPIPE','prism johnson':'PRISMJOHN',
    'privi speci.':'PRIVISCL','protean egov':'PROTEAN',
    'prudent corp.':'PRUDENT','ptc india':'PTC',
    'ptc india fin':'PTCIL','pnc infratech':'PNCINFRA',
    'piramal finance.':'PIRAMALFINAN','piramal pharma':'PIRAMPHARMA',
    'pvr inox':'PVRINOX','puravankara':'PURVA',
    'punjab chemicals':'PUNJABCHEM','pun. & sind bank':'PSB',
    'psbgrants':'PSBGRANTS','park medi world':'PARKMEDIWORLD',
    'pnb gilts':'PNBGILTS','precision camshf':'PRECAM',
    'park medi world':'PARKMEDIWORLD','paushak':'PAUSHAK',
    'prabha energy':'PRABHA',
    # Q
    'quadrant future':'QUADRANTFUTURE','quality power el':'QUALITYPOW',
    'quess corp':'QUESS',
    # R
    'r r kabel':'RRKABEL','r systems intl.':'RSYSTEMS',
    'racl geartech':'RACL','radico khaitan':'RADICO',
    'raghav product.':'RAGHAVPRO','railtel corpn.':'RAILTEL',
    'rain industries':'RAIN','rainbow child.':'RAINBOW',
    'rajesh exports':'RAJESHEXPO','rajesh power':'RAJESHPOW',
    'rajoo engineers':'RAJOOENG','rajputana stain.':'RAJPUTANAST',
    'rajratan global':'RAJRATAN','rallis india':'RALLIS',
    'ram ratna wires':'RAMRATNA','ramkrishna forg.':'RAMKRISHNA',
    'ramco inds.':'RAMCOINDS','ramco systems':'RAMCOSYS',
    'ramky infra':'RAMKY','rane (madras)':'RANEHOLDIN',
    'rane holdings':'RANEHOLDIN','rashi peripheral':'RPSL',
    'rategain travel':'RATEGAIN','rattanindia ent':'RATTANINDIA',
    'rattanindia pow.':'RATTANINDIAPOWER','raymond':'RAYMOND',
    'raymond lifestyle':'RAYMONDLSL','raymond lifestyl':'RAYMONDLSL',
    'raymond realty':'RYMONDREAL','rbl bank':'RBLBANK',
    'redington':'REDINGTON','redtape':'REDTAPE',
    'refex industries':'REFEX','relaxo footwear':'RELAXO',
    'reliance infra.':'RELINFRA','reliance power':'RPOWER',
    'religare enterp.':'RELIGARE','renaiss. global':'RENAISSANCE',
    'repco home fin':'REPCOHOME','responsive ind':'RESPONIND',
    'restaurant brand':'RBA','rhi magnesita':'RHIMGF',
    'rites':'RITES','rico auto inds':'RICO',
    'rolex rings':'ROLEXRINGS','rossari biotech':'ROSSARI',
    'rossell techsys':'ROSSELLTECH','roto pumps':'ROTOPUMPS',
    'route mobile':'ROUTE','rpg lifescience.':'RPGLIFE',
    'rpsg ventures':'RPSGVENT','rrp defense':'RRPD',
    'rrpsemiconductor':'RRPS','rubicon research':'RUBICONRES',
    'rupa & co':'RUPA','rhetan tmt ltd':'RHETANTMT',
    'roadstar infra':'ROADSTAR','rishabh instrum.':'RISHABH',
    'rir power electr':'RIRPOWER','rc f':'RCF',
    'r c f':'RCF',
    # S
    's h kelkar & co.':'SHKPHARMA','s p apparels':'SPAL',
    's p i c':'SPIC','saatvik green':'SAATVIKG',
    'safari inds.':'SAFARI','safe enterprises':'SAFEENT',
    'sai life':'SAILIFE','sai parenteral\'s':'SAIPHARMA',
    'sai silks':'SAISILKS','saksoft':'SAKSOFT',
    'salzer electron.':'SALZERELEC','sammaan capital':'SAMMAANCAP',
    'sambhv steel':'SAMBHVSTEEL','sandhar tech':'SANDHAR',
    'sandur manganese':'SANDUMA','sanathan textile':'SANATHAN',
    'sanstar':'SANSTAR','sansera enginee.':'SANSERA',
    'sakar healthcare':'SAKAR','saregama india':'SAREGAMA',
    'sarda energy':'SARDAEN','saraswati commer':'SARACOM',
    'sasken technol.':'SASKEN','satin creditcare':'SATIN',
    'savita oil tech':'SAVITA','sbc exports':'SBCEXPORTS',
    'sbfc finance':'SBFC','sci':'SCI',
    'sedemac mechatro':'SEDEMAC','seamec ltd':'SEAMECLTD',
    'senco gold':'SENCOGOLD','senores pharma.':'SENORESP',
    'servotech renew':'SERVOTECH','seshasayee paper':'SESHAPAPER',
    'seshaasai tech.':'SESHASAI','sg finserve':'SGFINSERVE',
    'sg mart':'SGMART','shaily engineer.':'SHAILYWIRE',
    'shankara buildpro':'SHANKARA','shanti educat.':'SHANTIEDULOG',
    'shanti gold':'SHANTIGOLD','shanthi gears':'SHANTIGEAR',
    'sh. digvijay cem':'SHDIGVIJAY','sh. pushkar chem.':'PUSHKAR',
    'sh.renuka sugar':'RENUKA','sharda cropchem':'SHARDACROP',
    'sharda motor':'SHARDAMOTR','sheela foam':'SHEELAFOAM',
    'shilchar tech.':'SHILCTECH','shilpa medicare':'SHILPAMED',
    'shivalik bimetal':'SHIVALIK','shoppers stop':'SHOPERSTOP',
    'shrem invit':'SHREMINVIT','shreeji ship. gl':'SHREEJISSHIP',
    'shriram pistons':'SHRIRAMPISTONS','shriram properti':'SHRIRAMPROPER',
    'shringar house':'SHRINGAR','shukra pharma.':'SHUKRAPHARM',
    'sigma advanced system':'SIGMAADVTECH','signpost india':'SIGNPOST',
    'silver touch':'SILVERTOUCH','sindhu trade':'SINDHU',
    'siyaram silk':'SIYARAM','sjs enterprises':'SJS',
    'skipper':'SKIPPER','skf india':'SKFINDIA',
    'skf india indus.':'SKFINDIA','sky gold & diam.':'SKYGOLD',
    'sml mahindra':'SMLISRGRP','sms pharma.':'SMSPHARMA',
    'sobha':'SOBHA','solex energy':'SOLEXENERG',
    'solara active':'SOLARA','som distilleries':'SOMDIST',
    'somany ceramics':'SOMANY','sona blw precis.':'SONACOMS',
    'sonata software':'SONATSOFTW','south ind.bank':'SOUTHBANK',
    'spandana sphoort':'SPANDANA','spicejet':'SPICEJET',
    'spml infra':'SPMLINFRA','sportking india':'SPORTKING',
    'star cement':'STARCEMENT','star health insu':'STARHEALTH',
    'stallion india':'STALLION',
    'standard engineering technology':'STANDARD',
    'steel exchange':'STEELEXCH','steel str. wheel':'SSWL',
    'steelcast':'STEELCAS','sterling & wils.':'SWSOLAR',
    'sterlite tech.':'STLTECH','stl networks':'STL',
    'stove kraft':'STOVEKRAFT','string metaverse':'STRMETAVER',
    'studds accessor.':'STUDDS','stylam industrie':'STYLAMIND',
    'styrenix perfor.':'STYRENIX','subros':'SUBROS',
    'sudarshan chem.':'SUDARSCHEM','sudeep pharma':'SUDEEPPHARMA',
    'summit securitie':'SUMITSYN','sumitomo chemi.':'SUMICHEM',
    'sun tv network':'SUNTV','sundram fasten.':'SUNDRMFAST',
    'sundrop brands':'SUNDROPS','suprajit engg.':'SUPRAJIT',
    'supriya lifesci.':'SUPRIYA','suraj estate':'SURAJEST',
    'suraksha diagno.':'SURAKSHA','sustainable ener':'SUSEN',
    'suven life scie.':'SUVENPHAR','swaraj engines':'SWARAJENG',
    'swan corp':'SWANCORP','swan defence':'SWANDEFENCE',
    'swelect energy':'SWELECT','syngene intl.':'SYNGENE',
    'syncom formul.':'SYNCOMF','syrma sgs tech.':'SYRMA',
    'sunteck realty':'SUNTECK','sjvn':'SJVN',
    'sis':'SIS','shadowfax technologies':'SHADOWFAX',
    'signatureglobal':'SIGNATURE','sepc':'SEPC',
    'shalby':'SHALBY','sapphire foods':'SAPPHIRE',
    'sagar cements':'SAGCEM','sanghi industrie':'SANGHIIND',
    'sangam india':'SANGAMIND','sunflag iron':'SUNFLAG',
    # T
    't r i l':'TRIL','tajgvk hotels':'TAJGVK',
    'talbros auto.':'TALBROS','tanfac inds.':'TANFAC',
    'tanla platforms':'TANLA','tarc ltd':'TARC',
    'tasty bite eat.':'TASTYBITE','tata chemicals':'TATACHEM',
    'tata comm':'TATACOMM','tata elxsi':'TATAELXSI',
    'tata inv.corpn.':'TATAINVEST','tata technolog.':'TATATECH',
    'tata tele. mah.':'TTML','tatva chintan':'TATVA',
    'tbo tek':'TBOTEK','tcpl packaging':'TCPLPACK',
    'team lease serv.':'TEAMLEASE','techno elec.engg':'TECHNOEL',
    'technocraf.inds.':'TECHNOCRAFT','technvision ven.':'TECHNVISION',
    'tega inds.':'TEGA','tejas networks':'TEJASNET',
    'tenneco clean':'TENNECOIND','texmaco infra.':'TEXINFRA',
    'texmaco infrast.':'TEXINFRA','texmaco rail':'TEXRAIL',
    'the anup enginee':'ANUPENG','the bombay burmah':'BBTC',
    'the hi-tech gear':'HITECH','the ramco cement':'RAMCOCEM',
    'thermax':'THERMAX','thirumalai chem.':'THIRUMALAI',
    'thangamayil jew.':'THANGAMAYL','thomas cook (i)':'THOMASCOOK',
    'thyrocare tech.':'THYROCARE','tilaknagar inds.':'TI',
    'titagarh rail':'TITAGARH','timex group':'TIMEXIND',
    'timken india':'TIMKEN','tinna rubber':'TINNARUBBER',
    'tips music':'TIPSFILMS','tour. fin. corp.':'TFCOFIN',
    'trident':'TRIDENT','transrail light':'TRANSRAIL',
    'triven.engg.ind.':'TRIVENI','triveni turbine':'TRITURBINE',
    'trualt bioenergy':'TRUALTBIO','ttk healthcare':'TTKHLTCARE',
    'ttk prestige':'TTKPRESTIG','tvs holdings':'TVSHLTD',
    'tvs infra. trust':'TVSINFRATRUST','tvs srichakra':'TVSSRICHAKRA',
    'tvs supply':'TVSSUPPLY','transport corp.':'TRANSCORP',
    'til':'TIL','tgv sraac':'TGVSRAAC',
    'ttk healthcare':'TTKHLTCARE','tsf investments':'TSFINVEST',
    't n merc. bank':'TAMILNADBK',
    # U
    'uco bank':'UCOBANK','uflex':'UFLEX',
    'ugro capital':'UGROCAP','ujaas energy':'UJAAS',
    'ujjivan small':'UJJIVANSFB','ultramarine pig.':'ULTRAMARINE',
    'uniparts india':'UNIPARTS','unichem labs.':'UNICHEMLAB',
    'unicommerce':'UNICOMMERCE','unitech':'UNITECH',
    'united breweries':'UBL','united foodbrands':'UNITEDF',
    'universal cables':'UNIVCABLES','updater services':'UPDATERSER',
    'urban company':'URBANCOMP','usha martin':'USHAMART',
    'utkarsh small f.':'UTKARSHBFL','uti amc':'UTIAMC',
    'ultramarine pig.':'ULTRAMARINE','ujjivan small':'UJJIVANSFB',
    # V
    'v-guard industri':'VGUARD','v-marc india':'VMARCIND',
    'v-mart retail':'VMART','v2 retail':'V2RETAIL',
    'vaibhav global':'VAIBHAVGBL','valiant commun.':'VALIANTCOMM',
    'valor estate':'VALORESTATE','vardhman hold.':'VARDHMANTM',
    'vardhman special':'VARDHSPECIAL','vardhman textile':'VARDHMAN',
    'varroc engineer':'VARROC','va tech wabag':'WABAG',
    'vedant fashions':'MANYAVAR','veedol corporat':'VEEDOL',
    'venky\'s (india)':'VENKYS','ventive hospital':'VENTIVE',
    'venus pipes':'VENUSPIPES','venus remedies':'VENUSREM',
    'veranda learning':'VERANDALT','vertis infra.':'VERTISINF',
    'vesuvius india':'VESUVIUS','vidhi specialty':'VIDHISPEC',
    'vidya wires':'VIDYAWIRES','vijaya diagnost.':'VIJAYA',
    'vikram solar':'VIKRAMSOLAR','vikran engg.':'VIKRANENGG',
    'vinati organics':'VINATIORGA','vinyas innovativ':'VINYAS',
    'vintage coffee':'VINTAGECOF','vishnu chemicals':'VISHNU',
    'viyash scientific':'VIYASHSCI','volt.transform.':'VOLTAMP',
    'vrl logistics':'VRLLOG','vst industries':'VSTIND',
    'vst till. tract.':'VSTIL','v i p inds.':'VIPIND',
    'virtuoso optoel.':'VIRTUOSO','viyash scientific':'VIYASHSCI',
    # W
    'wakefit innovati':'WAKEFIT','walchan. inds.':'WALCHANNAG',
    'welspun corp':'WELCORP','welspun enterp':'WELSPUNLIVING',
    'welspun living':'WELSPUNLIVING','welspun special.':'WSSL',
    'wendt india':'WENDT','west coast paper':'WESTCOAST',
    'westlife food':'WESTLIFE','wheels india':'WHEELS',
    'whirlpool india':'WHIRLPOOL','windlas biotech':'WINDLAS',
    'wonder electric.':'WONDERE','wonderla holiday':'WONDERLA',
    'wockhardt':'WOCKPHARMA','wpil':'WPIL',
    'waaree renewab.':'WAAREEENER','websol energy':'WEBELSOLAR',
    'western carriers':'WESTCARRIND','windsor machines':'WINDSORMA',
    # X
    'xpro india':'XPROINDIA',
    # Y
    'yasho industries':'YASH','yash highvoltage':'YASHHV',
    'yatharth hospit.':'YATHARTH','yatra online':'YATRA',
    # Z
    'zaggle prepaid':'ZAGGLE','zee entertainmen':'ZEEL',
    'zen technologies':'ZENTEC','zensar tech.':'ZENSARTECH',
    'zota health care':'ZOTA','zuari agro chem.':'ZUARI',
    'zydus wellness':'ZYDUSWEL',
    '5paisa capital':'5PAISA','63 moons tech.':'63MOONS',
    '360 one':'360ONE','3b blackbio':'3BBLACKBIO',
    '3m india':'MMIND',
}

NAME_SECTOR = [
    (["pharma","medic","drug","lifesci","bioscien","biotech",
      "astrazen","natco","ajanta","caplin","supriya","rpg life",
      "jb chem","jagson","corona rem","rubicon","beta drug",
      "bliss gvs","orchid","novartis","windlas","lincoln","kwality",
      "senores","akums","emcure","ipca","granules","strides",
      "alembic","marksans","jubilant phar","neuland","syncom",
      "cohance","piramal ph","solara","suven","wockh"],   "Pharmaceuticals"),
    (["health","hospital","diagnost","pathlabs","thyro",
      "vimta","gpt health","alivus","indrapr","medi","rainbow",
      "global health","narayana","aster","krsnaa","metropolis",
      "medplus","suraksha","dr agarwal","yatharth","sai life",
      "artemis","nephro","ventive"],                      "Healthcare"),
    (["bank"],                                            "Banking"),
    (["financ","capital","wealth","robeco","prudent",
      "rathi","authum","iifl","kfin","care rat",
      "algoquant","monarch","dam cap","crisil","icra",
      "sbfc","arman","satin","paisalo","mas fin",
      "repco","home first","aavas","aptus","india shelte",
      "ugro","bajaj fin","cholamand","muthoot","manappuram",
      "edelweiss","geojit","angel one","share india","smcglobal",
      "centrum","religare","fusion","fedbank","capri",
      "northern arc","indostar","mufin","aye fin",
      "creditacc","spandana","equitas","ujjivan","utkarsh",
      "suryoday","esaf","jana","sammaan","fino pay"],     "Finance"),
    (["software","tech","infosy","digit","infosec","system",
      "solution","netweb","sonata","birla","newgen","ceinsys",
      "cigniti","expleo","rsystem","ivalue","dynacons",
      "hexaware","kpit","tanla","blackbox","seshaasai",
      "indegene","inventurus","unicommerce","intellect design",
      "mastek","coforge","infobeans","datamatics","excelsoft",
      "sasken","latent view","nazara","rategain","cartrade",
      "route mobile","capillary","fractal","e2e","affle",
      "moschip","zensar","birlasoft","mphasis","happiest",
      "cyient","colab","axiscades"],                     "IT"),
    (["auto","motor","wagon","axle","tyre","gabriel",
      "carraro","sharda","pricol","sml","mswil",
      "force mot","swaraj","varroc","minda","jtekt",
      "subros","jamna","lumax","talbros","rane",
      "gna axle","sansera","craftsman","endurance",
      "escorts","apollo tyre","ceat","jk tyre",
      "balkrisind","belrise"],                            "Automobiles"),
    (["chemical","chemi","agrochem","agri","fineotex",
      "epigral","ghcl","sumic","styrenix","kingfa",
      "bayer","dhanuka","jublagri","krishnaph",
      "bn agro","privi","tatva","navin fluo","hikal",
      "vinati","aether","rossari","camlin","vidhi",
      "atul","galaxy surfact","sudarshan","laxmi chem",
      "neogen","gujarat fluo","gujarat alkali",
      "thirumalai","oriental arom","nocil","anupam"],    "Chemicals"),
    (["solar","power","energy","electric","renew",
      "turbine","insolation","kp green","saatvik",
      "vikram sol","emmvee","websol","advait",
      "danish pow","gk energy","oriana","solex",
      "solarworld","waaree","kpi green","torrent pow",
      "ola electric","ather","swelect","ujaas",
      "genus pow","inox green","inox wind","jp power",
      "sjvn","ptc india","rattanindia pow","guj inds",
      "orient green"],                                   "Power"),
    (["cement","cemindia","jk lakshmi","star cement",
      "heidelberg","mangalam cem","orient cement",
      "prism johnson","ramco cement","nuvoco","birla corp",
      "sanghi","sagar cem","dalmia","acc"],               "Cement"),
    (["steel","metal","copper","alumin","iron","alloys",
      "maithan","jai balaji","ratnamani","godawari",
      "himadri","gravita","steelcast","sandur",
      "shyam metalics","gallantt","kalyani steel",
      "usha martin","jsw","msp steel","sunflag",
      "heg","graphite","electrost","nmdc","tata chem",
      "tata steel","mishra dhatu","prakash","beml",
      "moil","kiocl"],                                   "Metals"),
    (["fmcg","consumer","hygiene","food","agro",
      "beverag","jyothy","emami","bajaj con",
      "heritage","dodla","gokul","piccadily",
      "vadilal","avanti","britannia","varun bev",
      "bikaji","gopal snack","prataap","mrs bect",
      "tasty bite","hatsun","adf food","l t food",
      "orkla","krbl","gm brew","united brew",
      "radico","som dist","sula","bcl ind",
      "balrampur","bannari","sh.renuka","ev ready",
      "bajaj hind","globus"],                            "FMCG"),
    (["realty","housing","infracon","construct","infra",
      "build","man infra","ashoka","bondada","knr",
      "enviro infra","srm","nbcc","gpt infra",
      "dilip","j kumar","h g infra","pnc","patel eng",
      "ceigall","anantam","ahluwalia","capacite","kolte",
      "ajmera","mahindra life","sobha","puravankara",
      "godrej indust","keystone","arihant sup","anant raj",
      "hubtown","spml","ramky","indiqube","embassy dev",
      "max estate","sunteck","prestige","brigade",
      "marathon","tarc","valor","signature","omaxe",
      "raymond realty","ashiana","shriram prop"],         "Real Estate"),
    (["hotel","travel","food serv","eih","benares",
      "eih assoc","tajgvk","oriental hotel","chalet",
      "samhi","lemon tree","mahindra hol","brigade hotel",
      "apeejay","wonderla","leela","juniper hotel",
      "thomas cook","easy trip","le travenues","ixigo",
      "itdc","global health"],                            "Hotels"),
    (["pump","engg","engineer","equip","machin",
      "elgi","ajax","td power","rajoo","kilburn",
      "elecon","concord control","jash","thejo",
      "vikran","macpower","volt","disa","isgec",
      "ksb","bharat bijlee","thermax","honeywell",
      "kennametal","kec","kalpataru","techno elec",
      "praj","ceat","bharat rasayan","wpil",
      "john cockerill","gmm pfaudler","bbe","hle",
      "carborundum","grindwell","timken","skf",
      "schaeffler","esab"],                              "Engineering"),
    (["defence","defense","aero","grse","zen tech",
      "bhansali","kernex","krishna def","unimech",
      "hbl","avantel","cochin shipyard","mtar",
      "paras defence","apollo micro","ideaforge",
      "mishra dhatu","gardener","rossell","centum",
      "data pattern","bharat electron"],                 "Defence"),
    (["media","music","studio","tips","panorama",
      "db corp","niit","string meta","sun tv",
      "zee entertain","jagran","saregama","balaji telef",
      "network18","hathway","prime focus","tv18"],        "Media"),
    (["telecom","tele","ttml","dlink","tata comm",
      "route mob","sterlite tech","hfcl","tejas",
      "stl","nelco"],                                     "Telecom"),
    (["logist","transport","cargo","railtel","rites",
      "irctc","transrail","guj pipav","knowledge mar",
      "vrl","tci express","blue dart","container corp",
      "allcargo","western carrier","mahindra logis",
      "tvs supply","updater","kapston","redington",
      "pds","rashi"],                                     "Logistics"),
    (["gold","jewel","diamond","gems","sky gold",
      "shanti gold","dp abhushan","shringar","goldiam",
      "thangamayil","senco","kalyan jewell",
      "p n gadgil","motisons","bluestone","laxmi goldorna",
      "kddl","khazanchi"],                               "Jewellery"),
    (["rubber","tinna","pix trans","apollo tyre",
      "ceat","jk tyre"],                                 "Tyres & Rubber"),
    (["pipe","tube","gandhi tube","venus pipe",
      "prince pipe","apollo pipe"],                      "Pipes & Tubes"),
    (["wire","cable","dynamic cab","precwire","vidya wire",
      "hind rect","vilas trans","rr kabel",
      "ram ratna","universal cable","finolex cable",
      "polycab","paramount comm"],                       "Cables & Wires"),
    (["textile","garment","stylam","vedant","manyavar",
      "page ind","redtape","studds","arvind",
      "vardhman","trident","raymond","indo count",
      "ktk","siyaram","dollar","lux ind","rupa",
      "monte carlo","kewal kir","sp apparel",
      "go fashion","cantabil","nitin spinner"],          "Textiles"),
    (["casting","forge","balu","amic","rolex",
      "happy forg","ramkrishna forg","mm forg",
      "alicon","craftsman","rane","sandhar"],            "Casting & Forging"),
    (["agri","seed","bombay super","krishna phos",
      "kaveri","eid parry","godrej agro","dhanuka",
      "bayer crop","pi ind","chambal fert","deepak fert",
      "coromandel","gnfc","gsfc","spic","rcf","gspcrops",
      "insecticid","india pesticide","sharda crop",
      "rallis","astec life"],                            "Agri"),
    (["packaging","pack","mold tek","uflex","epl",
      "tarcl","tcpl","flair","all time plastic",
      "carysil","borosil"],                              "Packaging"),
    (["bearing","nrb","skf","timken","schaeffler",
      "suprajit","lg bala"],                             "Auto Components"),
]

def _infer_sector(name: str) -> str:
    n = name.lower()
    for keywords, sector in NAME_SECTOR:
        if any(k in n for k in keywords):
            return sector
    return "Miscellaneous"


def _get_ticker(name: str) -> str:
    key = name.strip().lower()
    if key in KNOWN_TICKERS:
        return KNOWN_TICKERS[key].upper() + ".NS"
    for k, v in KNOWN_TICKERS.items():
        min_len = min(len(k), len(key))
        if min_len >= 5 and key[:min_len] == k[:min_len]:
            return v.upper() + ".NS"
    clean = re.sub(r"\b(ltd|limited|india|pvt|private|corp|inc|co|and|the|&)\b",
                   "", key, flags=re.IGNORECASE)
    clean = re.sub(r"[^a-z0-9]", "", clean).upper()[:10]
    return (clean or re.sub(r"[^A-Z0-9]", "", name.upper())[:10]) + ".NS"


def _parse_num(val) -> float:
    if pd.isna(val): return 0.0
    try: return float(str(val).replace(",","").replace("%","").strip())
    except: return 0.0


def build_from_csv(csv_path: Path = EXPORT_PATH,
                   min_mcap: float = 1000,
                   max_mcap: float = 999999) -> int:

    if not csv_path.exists():
        print(f"\n[ERROR] File not found: {csv_path}")
        print("Save your screener export as data/screener_export.csv")
        sys.exit(1)

    print(f"\nReading: {csv_path}")
    df = pd.read_csv(csv_path, encoding="latin-1", on_bad_lines="skip")
    df.columns = [re.sub(r"[\xa0\r\n\t]+", " ", c).strip() for c in df.columns]
    print(f"Rows: {len(df)}")

    col_name  = next((c for c in df.columns if c.lower().strip() == "name"), None)
    col_mcap  = next((c for c in df.columns if "mar cap" in c.lower()), None)
    col_pe    = next((c for c in df.columns if c.strip().lower() in ("p/e","pe")), None)
    col_pb    = next((c for c in df.columns if "cmp / bv" in c.lower() or "p/b" in c.lower()), None)
    col_roe   = next((c for c in df.columns if c.strip().lower().startswith("roe %")), None)

    if not col_name or not col_mcap:
        print(f"[ERROR] Cannot find required columns. Found: {list(df.columns)}")
        sys.exit(1)

    df["_mcap"] = df[col_mcap].apply(_parse_num)
    df_filtered = df[(df["_mcap"] >= min_mcap) & (df["_mcap"] <= max_mcap)].copy()
    print(f"After mcap filter (>{min_mcap} Cr): {len(df_filtered)} stocks")

    now, rows, seen = datetime.now().isoformat(), [], set()

    for _, row in df_filtered.iterrows():
        name = str(row[col_name]).strip()
        if not name or name.lower() == "nan":
            continue
        ticker      = _get_ticker(name)
        screener_id = ticker.replace(".NS","").replace(".BO","")
        base, n = ticker, 1
        while ticker in seen:
            ticker = base.replace(".NS", f"_{n}.NS")
            n += 1
        seen.add(ticker)

        rows.append({
            "ticker":        ticker,
            "name":          name,
            "sector":        _infer_sector(name),
            "screener_id":   screener_id,
            "market_cap_cr": _parse_num(row["_mcap"]),
            "pe":            _parse_num(row[col_pe])  if col_pe  else 0.0,
            "pb":            _parse_num(row[col_pb])  if col_pb  else 0.0,
            "roe":           _parse_num(row[col_roe]) if col_roe else 0.0,
            "added_on":      now,
        })

    upsert_universe(rows)
    print(f"\n[Done] {len(rows)} stocks loaded into universe.")
    print("\nSector breakdown:")
    counts = Counter(r["sector"] for r in rows)
    for sector, count in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {sector:<28} {count}")
    return len(rows)


def print_summary():
    df = get_universe()
    if df.empty: print("Universe empty."); return
    print(f"\nUniverse: {len(df)} stocks")


if __name__ == "__main__":
    init_db()
    build_from_csv()
    print_summary()
    print("\nNext: python batch_scraper.py")
